#index:
#    path: /
#    controller: App\Controller\DefaultController::index

gesdinet_jwt_refresh_token:
    path:     /token/refresh
    defaults: { _controller: gesdinet.jwtrefreshtoken:refresh }

swagger_ui:
    path: /apidoc
    controller: api_platform.swagger.action.ui